"""Add national_id to Tenant

Revision ID: 0237c61fa2bb
Revises: 1474a331904c
Create Date: 2025-07-03 11:14:12.378063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0237c61fa2bb'
down_revision = '1474a331904c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('national_id')

    # ### end Alembic commands ###
