"""Add utility_bill_types and unit_numbers to Property

Revision ID: 1474a331904c
Revises: 
Create Date: 2025-07-03 11:07:31.510815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1474a331904c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utility_bill_types', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('unit_numbers', sa.Text(), nullable=False))
        batch_op.drop_column('utility_bill')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utility_bill', sa.TEXT(), nullable=True))
        batch_op.drop_column('unit_numbers')
        batch_op.drop_column('utility_bill_types')

    # ### end Alembic commands ###
