"""Add paybill and fees to Property

Revision ID: 2241e04012de
Revises: 0237c61fa2bb
Create Date: 2025-07-03 22:25:14.112864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2241e04012de'
down_revision = '0237c61fa2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('paybill_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fees', sa.Numeric(10, 2), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('fees')
        batch_op.drop_column('paybill_number')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
