"""Make tenant.property_id nullable

Revision ID: 8bb5e933f806
Revises: 
Create Date: 2025-07-02 11:20:41.411936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bb5e933f806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
