"""Add is_offline field to Payment

Revision ID: a04875e81e37
Revises: c69bb2f7978e
Create Date: 2025-06-30 10:35:51.260384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04875e81e37'
down_revision = 'c69bb2f7978e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_offline', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('is_offline')

    # ### end Alembic commands ###
